
# All services to set up
services:
  caddy:
    # Build from a specific image
    build:
      # Set build context to project root
      context: .
      # Where to find the Dockerfile for frontend service    
      dockerfile: ./src/caddy/Dockerfile 
    # load env vars from file
    env_file: .env 
    # which services it can talk to from within the container's network
    networks:
      - int
    volumes: 
      - ./src/caddy/Caddyfile:/etc/caddy/Caddyfile # bind mount
      - public_html:/var/www/frontend # shares frontend assets with website
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
      - "${HTTPS_PORT}:${HTTPS_PORT}"
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
      - "${APP_PORT}:4000"

    depends_on:
      - website # ensures website builds the volume and caddy service/container syncs with it

  website:
    build:
      # Set build context to project root
      context: . 
      # Where to find the Dockerfile for frontend service    
      dockerfile: ./src/website/Dockerfile 
    # load env vars from file
    env_file: .env 
    volumes:
      - public_html:/var/www/frontend # shares frontend assets with caddy
    networks:
      - int # caddy can communicate especially with backend

networks:
  int: 
    external: true
    name: website2-caddy-bridge

volumes:
  public_html:
